services:
  mongo:
    image: mongo:6
    container_name: dd-mongo
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db

  backend:
    image: mrdevine/discover-dollar-backend:latest
    container_name: dd-backend
    restart: unless-stopped
    environment:
      - MONGO_URL=mongodb://mongo:27017/bezkoder_db
      - PORT=8080
    depends_on:
      - mongo
    ports:
      - "8080:8080"

  frontend:
    image: mrdevine/discover-dollar-frontend:latest
    container_name: dd-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "8081:80"

volumes:
  mongo_data:
